kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-name
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
