apiVersion: v1
kind: Service

metadata:
  name: fb-database-service
  labels:
    app: fb-database
    
spec:
  # If you want to make sure that connections from a particular client are passed to the same Pod each time
  # sessionAffinity: ClientIP # track using client IP address
  # sessionAffinity: None # default
  selector:
    app: fb-database
  type: LoadBalancer # default round robin
  #externalIPs:
  #- 192.168.0.105
  ports:
     - port: 5432 # outside port
       targetPort: 5432 # container port
       nodePort: 30001
       
