apiVersion: v1
kind: Service

metadata:
  name: myservice
  labels:
    app: nginx
    
spec:
  # If you want to make sure that connections from a particular client are passed to the same Pod each time
  # sessionAffinity: ClientIP
  # sessionAffinity: None # default
  selector:
    app: nginx
  type: LoadBalancer
  #externalIPs:
  #- 192.168.0.105
  ports:
     - nodePort: 30000
       port: 80
       targetPort: 80
