apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: nginx-server-replica

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: nginx-server-replica
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

  
# # same as kubectl autoscale rs nginx-server-replica --max=10 --min=3 --cpu-percent=50
