apiVersion: v1
kind: Pod

metadata:
  name: pod1
  labels:
    tier: nginx-server
spec:
  containers:
  - name: nginx1-container
    image: nginx:latest
    ports:
     - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Pod

metadata:
  name: pod2
  labels:
    tier: nginx-server

spec:
  containers:
  - name: nginx2-container
    image: nginx:latest
    ports:
     - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"